# Generated by Django 4.0.5 on 2022-06-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giftcards',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('credit_remaining', models.IntegerField(default=25)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Giftcard',
                'verbose_name_plural': 'Giftcards',
            },
        ),
    ]
