# Generated by Django 4.0.5 on 2022-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('probability_heads', models.DecimalField(decimal_places=2, max_digits=3)),
                ('probability_tails', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
